spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:E:/test/h2test/community
    username: root
    password: ******

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml